In [1]:
import numpy as np

In [2]:
# Creating df
A = np.array([
        [ 3,  7],
        [-4, -6],
        [ 7,  8],
        [ 1, -1],
        [-4, -1],
        [-3, -7]
    ])

In [3]:
A

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [4]:
A.shape

(6, 2)

In [13]:
# Checking if the dataset is in Standard Normal Distribution (mean=0, std=1)

np.mean(A), np.std(A[1])

(0.0, 1.0)

In [10]:
# Converting array to df
import pandas as pd
df = pd.DataFrame(A, columns=['a0', 'a1'])

In [11]:
df

a0  a1
0   3   7
1  -4  -6
2   7   8
3   1  -1
4  -4  -1
5  -3  -7

In [24]:
# Finding covariances between two columns cov = sum of all rows((c1-mean(c1)) (c2-mean(c2)))/ m-1
#cov = E((3-0)(7-0))/5 + ((-4-0)(-6-0))/5 + etc

a0 = A[:,0] # All rows first column
a1 = A[:,1] # All rows second column

np.cov(a0,a1)

array([[20., 25.],
       [25., 40.]])

In [26]:
np.sum(a0*a1)/5 # Covariance for col1, row 1

25.0

In [27]:
A.T @ A/5 # Covariance with transpose and matrix multiplication

array([[20., 25.],
       [25., 40.]])

In [28]:
sigma = A.T @ A/5

In [30]:
# eigenvalues value of the vector

np.linalg.eig(sigma)

(array([ 3.07417596, 56.92582404]),
 array([[-0.82806723, -0.56062881],
        [ 0.56062881, -0.82806723]]))

First aray is storing the eigenvalues. The second of these values is lambda (first principal component - higher value). The first value is the second principal component (lower value).

In [31]:
l, x = np.linalg.eig(sigma)

In [32]:
l

array([ 3.07417596, 56.92582404])

In [33]:
x

array([[-0.82806723, -0.56062881],
       [ 0.56062881, -0.82806723]])

In [34]:
# Calculating PC1
sigma @ x[:,0]

array([-2.54562438,  1.72347161])

In [35]:
sigma @ x[:,1]

array([-31.91425695, -47.13840945])

In [38]:
# Transforming data
pc1_arr = A @ x[:,1] # Multiplying by first princiapl component
pc2_arr = A @ x[:,0] # Multipying by second principal component

### Decomposing for another dataset?