In [2]:
import numpy as np

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array([[1,3], [3,4]])

array([[1, 3],
       [3, 4]])

In [5]:
np.array([[1,3], [3,4], [6,7,8]])

C:\Users\kskua\AppData\Local\Temp/ipykernel_9748/1024472721.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3], [3,4], [6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [6]:
np.array([[[1,3], [3,4]], [[1,3], [3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [7]:
np.array([1,2,3], ndmin = 3) # Creating array with 3 dimensions

array([[[1, 2, 3]]])

In [8]:
np.array([1,2,3], dtype=complex) # Converting array to complex type

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
np.array([(1,2), (4,5)]) # We can create arrays with both list and tuples

array([[1, 2],
       [4, 5]])

In [10]:
ar = np.array([[1,3], [3,4]], dtype = [('a', '<i4'), ('b', '<i8')])

In [11]:
type(ar[0][0])

numpy.void

In [12]:
type(ar[1][1])

numpy.void

In [13]:
ar = np.array([[1,3], [3,4]])

In [14]:
ar[0], ar[0][0], ar[0][1]

(array([1, 3]), 1, 3)

In [15]:
ar[1]

array([3, 4])

In [16]:
type(ar[1][0])

numpy.int32

In [17]:
np.mat(ar)

matrix([[1, 3],
        [3, 4]])

In [18]:
type(ar)

numpy.ndarray

In [19]:
np.matrix(ar) # Creating matrix

matrix([[1, 3],
        [3, 4]])

In [20]:
m = np.matrix(ar) # Creating matrix

In [21]:
np.asarray(ar)

array([[1, 3],
       [3, 4]])

In [22]:
issubclass(np.ndarray, np.matrix)

False

In [23]:
a = ar # Shallow copy

In [24]:
b = np.copy(ar) # Deep copy

In [25]:
#Changing value in array
ar[0][1] = 67

In [26]:
ar

array([[ 1, 67],
       [ 3,  4]])

In [28]:
a # A - solo copy - is affected by the change. We can change array eleements. Arrays are mutable.

array([[ 1, 67],
       [ 3,  4]])

In [27]:
b #B  - deep copy - is holding previous values

array([[1, 3],
       [3, 4]])

In [29]:
for i in ar:
    print(i)

[ 1 67]
[3 4]


In [30]:
for i in ar:
    for j in i:
        print(j)

1
67
3
4


In [32]:
np.fromfunction(lambda i,j: i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [33]:
np.fromfunction(lambda i,j: i**j, (3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [38]:
gen =(i*i for i in range(5))

In [35]:
def test(x):
    yield x

In [36]:
test(5)

<generator object test at 0x000002510541FA50>

In [39]:

for i in gen:
    print(i)

0
1
4
9
16


In [40]:
np.fromstring('1,3,4,5,6', sep=',', dtype=int)

array([1, 3, 4, 5, 6])

In [43]:
ar1 = np.array([[1,2,3,], [2,3,4], [3,4,5]])

In [44]:
ar1.ndim

2

In [45]:
ar1.size, ar1.shape

(9, (3, 3))

In [46]:
ar1.dtype

dtype('int32')

In [49]:
big_a = np.array([ar1, ar1])

In [52]:
big_a

array([[[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]]])

In [50]:
big_a.ndim

3

In [51]:
big_a.shape

(2, 3, 3)

In [53]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [55]:
np.arange(6.6, 15, 0.1) # Creating array in range with step 0.1

array([ 6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9,
       11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ,
       12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1,
       13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9])

In [58]:
np.linspace(1,10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [59]:
np.zeros(2)

array([0., 0.])

In [60]:
np.zeros_like(ar)

array([[0, 0],
       [0, 0]])

In [63]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [64]:
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [66]:
np.empty((2,2,4))

array([[[4.67296746e-307, 1.69121096e-306, 1.20161797e-306,
         8.34441742e-308],
        [1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
         6.89807188e-307]],

       [[7.56594375e-307, 6.23060065e-307, 1.78021527e-306,
         8.34454050e-308],
        [1.11261027e-306, 1.15706896e-306, 1.33512173e-306,
         8.34402698e-308]]])

In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.linspace([2,4],4, endpoint=False, axis=1)

array([[2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96],
       [4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  ]])

In [70]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

## Useful NumPy functions

### Creating data

In [71]:
a = np.linspace(1, 20, 30) # Creating 30 instances

In [72]:
a.ndim

1

In [73]:
a.shape

(30,)

We have created a 30 instances in numpy array, but we have only 1 dimensional data. Let's reshape it to make it columns wise. 

### Reshaping

In [74]:
a.reshape(30,1)

array([[ 1.        ],
       [ 1.65517241],
       [ 2.31034483],
       [ 2.96551724],
       [ 3.62068966],
       [ 4.27586207],
       [ 4.93103448],
       [ 5.5862069 ],
       [ 6.24137931],
       [ 6.89655172],
       [ 7.55172414],
       [ 8.20689655],
       [ 8.86206897],
       [ 9.51724138],
       [10.17241379],
       [10.82758621],
       [11.48275862],
       [12.13793103],
       [12.79310345],
       [13.44827586],
       [14.10344828],
       [14.75862069],
       [15.4137931 ],
       [16.06896552],
       [16.72413793],
       [17.37931034],
       [18.03448276],
       [18.68965517],
       [19.34482759],
       [20.        ]])

In [79]:
a.reshape(2,1, 15) # Reshape number of instances must always equal the number of instances in original array (2*1*15 = 30)

array([[[ 1.        ,  1.65517241,  2.31034483,  2.96551724,
          3.62068966,  4.27586207,  4.93103448,  5.5862069 ,
          6.24137931,  6.89655172,  7.55172414,  8.20689655,
          8.86206897,  9.51724138, 10.17241379]],

       [[10.82758621, 11.48275862, 12.13793103, 12.79310345,
         13.44827586, 14.10344828, 14.75862069, 15.4137931 ,
         16.06896552, 16.72413793, 17.37931034, 18.03448276,
         18.68965517, 19.34482759, 20.        ]]])

## Generating random data

In [80]:
np.random.rand(20) # Generates random uniform data - instances with equall possibility to occurr - flat distribution

array([0.68709588, 0.32798284, 0.61113332, 0.52136253, 0.46921605,
       0.35170836, 0.30805906, 0.54340198, 0.5818194 , 0.72844774,
       0.38083066, 0.57205696, 0.0165756 , 0.59987495, 0.06277739,
       0.60195435, 0.1012997 , 0.53830771, 0.12289696, 0.04322858])

In [81]:
np.random.rand(2,2,3)

array([[[0.11851981, 0.76451289, 0.91427047],
        [0.45022544, 0.77981008, 0.96785116]],

       [[0.27410001, 0.80770661, 0.90678982],
        [0.08783063, 0.5459125 , 0.6326393 ]]])

In [82]:
np.random.randint(1,10,5) # Generates random integers

array([6, 8, 1, 4, 4])

## Built-in functions, slicing

In [83]:
b = np.random.randint(4,10, (5,5))

In [84]:
b

array([[4, 6, 8, 4, 8],
       [5, 7, 8, 5, 8],
       [4, 7, 7, 6, 8],
       [5, 8, 6, 7, 6],
       [6, 5, 8, 4, 9]])

In [85]:
b.max()

9

In [86]:
b.min()

4

In [88]:
b[0:2, 3: ] #Rows, Columns

array([[4, 8],
       [5, 8]])

In [89]:
b> 5

array([[False,  True,  True, False,  True],
       [False,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True, False,  True, False,  True]])

In [90]:
b[b>5]

array([6, 8, 8, 7, 8, 8, 7, 7, 6, 8, 8, 6, 7, 6, 6, 8, 9])

### Operations on arrays

In [91]:
c = np.random.randint(2,4,(3,3))

In [92]:
d = np.random.randint(2,4,(3,3,))

In [93]:
c

array([[3, 3, 2],
       [2, 2, 3],
       [2, 3, 3]])

In [94]:
d

array([[3, 2, 2],
       [3, 3, 3],
       [2, 2, 2]])

In [95]:
#Multiplication element wise - working only on arrays with the same number of dimensions
c*d

array([[9, 6, 4],
       [6, 6, 9],
       [4, 6, 6]])

In [96]:
#Matrix multiplication
c@d

array([[22, 19, 19],
       [18, 16, 16],
       [21, 19, 19]])

In [97]:
c/0

C:\Users\kskua\AppData\Local\Temp/ipykernel_9748/97081324.py:1: RuntimeWarning: divide by zero encountered in true_divide
  c/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

### Broadcasting

In [99]:
e = np.zeros((3,4))

In [100]:
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
a = np.array([1,2,3,4])

In [102]:
a

array([1, 2, 3, 4])

In [103]:
e + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

#### Broadcasting and reshaping
When dimension are not equal we can reshape it

In [104]:
f = np.array([5,6,7])

In [105]:
f

array([5, 6, 7])

In [106]:
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
f + e # This will not work - different shapes

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [107]:
f.reshape(3,1) + e # Reshaping 1d arrays made the brodcasting possible

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [109]:
f.reshape(3,1) # Reshaped into 3d array

array([[5],
       [6],
       [7]])

Same thing as above, but with a use of a Transpose.

! Note that array for this operation needs to be 2d. 

In [110]:
g = np.array([[5,6,7]])

In [111]:
g.ndim

2

In [112]:
g.T

array([[5],
       [6],
       [7]])

## Advanced functions in NumPy

In [113]:
np.exp(c)

array([[20.08553692, 20.08553692,  7.3890561 ],
       [ 7.3890561 ,  7.3890561 , 20.08553692],
       [ 7.3890561 , 20.08553692, 20.08553692]])

In [114]:
np.log10(c)

array([[0.47712125, 0.47712125, 0.30103   ],
       [0.30103   , 0.30103   , 0.47712125],
       [0.30103   , 0.47712125, 0.47712125]])

In [115]:
np.sqrt(c)

array([[1.73205081, 1.73205081, 1.41421356],
       [1.41421356, 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 1.73205081]])

## Random seed

In [123]:
np.random.seed(42)

In [127]:
np.random.binomial(0,1,size= 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])